<?php
/**
 * Outputs a component request form in the admin footer.
 * This function checks for the presence of a 'post' GET parameter and verifies if the user is an admin.
 * If both conditions are met, it constructs an admin URL, and triggers a custom action hook 'component_request_form',
 * passing the admin URL and current user object as parameters.
 * The HTML generated by hooked functions is captured and outputted here.
 *
 * @return void
 */
function ks_component_request_form() {
    // Ensure 'post' GET parameter is set and the user has admin privileges
    if (  !  isset( $_GET['post'] ) || !  is_admin() ) {
        return;
    }

    // Get the current user object
    $current_user = wp_get_current_user();

    // Make $pagenow variable accessible within the function
    global $pagenow;

    // Get the WordPress Admin Base URL
    $admin_url = admin_url( $pagenow );

    // Get the Query String if available
    $query_string = $_SERVER['QUERY_STRING'];

    // Construct the full URL, append the query string if it's not empty
    $admin_url .=  !  empty( $query_string ) ? '?' . $query_string : '';

    // === HTML Form Construction ===
    // Start output buffering to capture any output from the action hook
    ob_start();

    // Trigger the 'component_request_form' action, passing the admin URL and current user as parameters
    // Hooked functions can use these parameters to generate HTML
    do_action( 'component_request_form', $admin_url, $current_user );

    // Get the buffered content and clean the buffer, then output it
    echo ob_get_clean();
}

// Hook 'ks_component_request_form' function to the 'admin_footer' action
// This will cause the function to be called in the footer of admin pages
add_action( 'admin_footer', 'ks_component_request_form' );